import streamlit as st
import pandas as pd
import numpy as np
import time
import joblib

# --- PAGE CONFIGURATION ---
st.markdown("## 📉 Customer Churn Prediction")
st.markdown("""
This tool uses a Machine Learning model to predict the probability 
of a bank customer leaving the service (Churn). Adjust the parameters below to simulate a customer profile.
""")

# --- SIDEBAR INPUTS ---
st.sidebar.header("📝 Customer Profile")

def user_input_features():
    # Demographic Data
    gender = st.sidebar.selectbox("Gender", ("Male", "Female"))
    age = st.sidebar.slider("Age", 18, 92, 30)
    geography = st.sidebar.selectbox("Country", ("France", "Spain", "Germany"))
    
    # Financial Data
    credit_score = st.sidebar.slider("Credit Score", 300, 850, 600)
    tenure = st.sidebar.slider("Tenure (Years)", 0, 10, 3)
    balance = st.sidebar.number_input("Account Balance ($)", 0.0, 250000.0, 60000.0)
    num_of_products = st.sidebar.selectbox("Number of Products", (1, 2, 3, 4))
    has_cr_card = st.sidebar.checkbox("Has Credit Card?", value=True)
    is_active_member = st.sidebar.checkbox("Is Active Member?", value=True)
    estimated_salary = st.sidebar.number_input("Estimated Salary ($)", 0.0, 200000.0, 50000.0)

    # Dictionary to hold the data (Matches typical dataset column names)
    data = {
        'CreditScore': credit_score,
        'Geography': geography,
        'Gender': gender,
        'Age': age,
        'Tenure': tenure,
        'Balance': balance,
        'NumOfProducts': num_of_products,
        'HasCrCard': 1 if has_cr_card else 0,
        'IsActiveMember': 1 if is_active_member else 0,
        'EstimatedSalary': estimated_salary
    }
    # Convert to DataFrame
    features = pd.DataFrame(data, index=[0])
    return features

df = user_input_features()

# --- MAIN INTERFACE ---

# 1. Display User Inputs
st.subheader("🔍 Customer Data")
st.dataframe(df, hide_index=True)

# 2. Prediction Logic (MOCKUP / SIMULATION)
# NOTE: Replace this function with your actual model prediction later
def predict_churn_simulated(input_data):
    # Dummy logic for visual demonstration purposes only
    score = 0
    if input_data['Age'][0] > 50: score += 30
    if input_data['IsActiveMember'][0] == 0: score += 20
    if input_data['NumOfProducts'][0] >= 3: score += 40
    if input_data['Balance'][0] == 0: score += 10
    
    # Return probability between 0 and 1
    prob = min(score + np.random.randint(0, 20), 100) / 100
    return prob

# 3. Prediction Button and Results
col1, col2 = st.columns([1, 2])

with col1:
    st.markdown("<br>", unsafe_allow_html=True) # Vertical spacer
    predict_btn = st.button("🚀 Calculate Churn Risk", type="primary")

with col2:
    if predict_btn:
        with st.spinner('Analyzing behavior patterns...'):
            time.sleep(1) # Simulate computation time
            
            # --- REAL INTEGRATION: prediction = model.predict_proba(df) ---
            probability = predict_churn_simulated(df)
            
            # Display Metric
            st.metric(label="Churn Probability", value=f"{probability*100:.1f}%")
            
            # Conditional Alert System
            if probability > 0.5:
                st.error("⚠️ HIGH RISK: This customer is likely to churn.")
                st.toast("Alert: High risk customer detected")
            else:
                st.success("✅ LOW RISK: This customer is likely to stay.")

# --- EXPLANATION TABS (NOTEBOOKLM CONTENT) ---
st.markdown("---")
tab1, tab2 = st.tabs(["📘 Model Explanation", "📊 Feature Importance"])

with tab1:
    st.markdown("""
    ### How does this model work?
    *(Use NotebookLM to generate this text based on your training code)*
    
    This model utilizes a **Gradient Boosting algorithm (XGBoost)** trained on a dataset of 10,000 bank customers.
    It evaluates non-linear relationships between age, balance, and activity status to determine loyalty.
    """)

with tab2:
    st.info("Place a static image generated by Matplotlib/SHAP here")
    # st.image("assets/feature_importance.png")
    st.markdown("""
    **Key Factors Influencing the Prediction:**
    1. **Age:** Older customers tend to have a higher churn rate.
    2. **Number of Products:** Having 3 or more products drastically increases risk.
    3. **Active Membership:** Inactive members are more likely to leave.
    """)
